In [3]:
import pandas as pd
sales = {
    "Day": [
        "Monday",
        "Monday",
        "Tuesday",
        "Tuesday",
        "Wednesday",
        "Wednesday"
    ],

    "Revenue": [
        500,
        700,
        1000,
        600,
        1500,
        300
    ]
}

df = pd.DataFrame(sales)

df

         Day  Revenue
0     Monday      500
1     Monday      700
2    Tuesday     1000
3    Tuesday      600
4  Wednesday     1500
5  Wednesday      300

In [5]:
df.groupby(df['Day']).sum()

           Revenue
Day
Monday        1200
Tuesday       1600
Wednesday     1800

In [6]:
df.groupby(df['Day']).mean()

           Revenue
Day
Monday       600.0
Tuesday      800.0
Wednesday    900.0

In [7]:
df.groupby(df['Day']).mean().idxmax()

Revenue    Wednesday
dtype: str

In [9]:
df.groupby(df['Day'])['Revenue'].count()

Day
Monday       2
Tuesday      2
Wednesday    2
Name: Revenue, dtype: int64

In [10]:
df.groupby('Day')['Revenue'].agg(['sum', 'mean', 'count'])

            sum   mean  count
Day
Monday     1200  600.0      2
Tuesday    1600  800.0      2
Wednesday  1800  900.0      2

In [11]:
df.groupby('Day')['Revenue'].agg(['sum', 'mean', 'max', 'min', 'count'])

            sum   mean   max  min  count
Day
Monday     1200  600.0   700  500      2
Tuesday    1600  800.0  1000  600      2
Wednesday  1800  900.0  1500  300      2

In [12]:
sales = {
    "Day": [
        "Monday",
        "Monday",
        "Tuesday",
        "Tuesday",
        "Wednesday",
        "Wednesday"
    ],

    "Category": [
        "Food",
        "Drinks",
        "Food",
        "Drinks",
        "Food",
        "Drinks"
    ],

    "Revenue": [
        500,
        700,
        1000,
        600,
        1500,
        300
    ]
}

df = pd.DataFrame(sales)

df

         Day Category  Revenue
0     Monday     Food      500
1     Monday   Drinks      700
2    Tuesday     Food     1000
3    Tuesday   Drinks      600
4  Wednesday     Food     1500
5  Wednesday   Drinks      300

In [13]:
df.groupby(['Day', 'Category'])['Revenue'].sum()

Day        Category
Monday     Drinks       700
           Food         500
Tuesday    Drinks       600
           Food        1000
Wednesday  Drinks       300
           Food        1500
Name: Revenue, dtype: int64

In [14]:
df.groupby(['Day', 'Category'])['Revenue'].mean()

Day        Category
Monday     Drinks       700.0
           Food         500.0
Tuesday    Drinks       600.0
           Food        1000.0
Wednesday  Drinks       300.0
           Food        1500.0
Name: Revenue, dtype: float64

In [15]:
df.groupby('Category')['Revenue'].max()

Category
Drinks     700
Food      1500
Name: Revenue, dtype: int64