In [1]:
import pandas as pd

In [9]:
sales = { 'Day': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
           'Revenue': [1200, 1500, 1800, 2200, 3500] }

In [10]:
df= pd.DataFrame(sales)
df

         Day  Revenue
0     Monday     1200
1    Tuesday     1500
2  Wednesday     1800
3   Thursday     2200
4     Friday     3500

In [16]:
total_revenue = df['Revenue'].sum()
print("Total Revenue:", total_revenue)

Total Revenue: 10200

In [17]:
maximum_revenue = df['Revenue'].max()
print("Maximum Revenue:", maximum_revenue)

Maximum Revenue: 3500

In [18]:
the_mean_revenue = df['Revenue'].mean()
print("Mean Revenue:", the_mean_revenue)

Mean Revenue: 2040.0

In [19]:
df['Day'][df['Revenue'] == maximum_revenue]

4    Friday
Name: Day, dtype: str

In [20]:
df.loc[df["Revenue"].idxmax()]

Day        Friday
Revenue      3500
Name: 4, dtype: object

In [21]:
df.loc[df['Day'].idxmax()]

Day        Wednesday
Revenue         1800
Name: 2, dtype: object

In [23]:
df[df['Revenue']>2000]

        Day  Revenue
3  Thursday     2200
4    Friday     3500

In [24]:
df.loc[df['Revenue']>1500]

         Day  Revenue
2  Wednesday     1800
3   Thursday     2200
4     Friday     3500