In [1]:
import pandas as pd

In [2]:
sales = {
    "Day": [
        "Monday",
        "Monday",
        "Tuesday",
        "Tuesday",
        "Wednesday",
        "Wednesday"
    ],

    "Category": [
        "Food",
        "Drinks",
        "Food",
        "Drinks",
        "Food",
        "Drinks"
    ],

    "Revenue": [
        500,
        700,
        1000,
        600,
        1500,
        300
    ]
}

df = pd.DataFrame(sales)

In [3]:
df

         Day Category  Revenue
0     Monday     Food      500
1     Monday   Drinks      700
2    Tuesday     Food     1000
3    Tuesday   Drinks      600
4  Wednesday     Food     1500
5  Wednesday   Drinks      300

In [4]:
df.pivot_table(
    values="Revenue",
    index="Day",
    columns="Category",
    aggfunc="sum"
)

Category   Drinks  Food
Day
Monday        700   500
Tuesday       600  1000
Wednesday     300  1500

In [5]:
df.pivot_table(
    values="Revenue",
    index="Day",
    columns="Category",
    aggfunc="mean"
)

Category   Drinks    Food
Day
Monday      700.0   500.0
Tuesday     600.0  1000.0
Wednesday   300.0  1500.0

In [6]:
import pandas as pd

sales = {
    "Day": [
        "Monday","Monday","Monday",
        "Tuesday","Tuesday","Tuesday",
        "Wednesday","Wednesday","Wednesday",
        "Thursday","Thursday","Thursday",
        "Friday","Friday","Friday","Friday","Friday",
        "Saturday","Saturday","Saturday","Saturday","Saturday",
        "Sunday","Sunday","Sunday"
    ],

    "Nationality": [
        "English","Irish","American",
        "English","Irish","American",
        "English","Irish","American",
        "English","Irish","American",
        "English","Irish","American","French","German",
        "English","Irish","American","French","German",
        "English","Irish","American"
    ],

    "Category": [
        "Beer","Beer","Food",
        "Beer","Cocktail","Food",
        "Beer","Cocktail","Food",
        "Beer","Cocktail","Food",
        "Beer","Cocktail","Food","Beer","Food",
        "Beer","Cocktail","Food","Beer","Food",
        "Beer","Cocktail","Food"
    ],

    "Revenue": [
        2500,1200,900,
        2800,1500,1100,
        3200,1800,1300,
        4000,2200,1800,
        8500,3500,2500,1800,1400,
        9500,4200,3000,2200,1700,
        5000,2500,1800
    ]
}

df = pd.DataFrame(sales)

df

          Day Nationality  Category  Revenue
0      Monday     English      Beer     2500
1      Monday       Irish      Beer     1200
2      Monday    American      Food      900
3     Tuesday     English      Beer     2800
4     Tuesday       Irish  Cocktail     1500
5     Tuesday    American      Food     1100
6   Wednesday     English      Beer     3200
7   Wednesday       Irish  Cocktail     1800
8   Wednesday    American      Food     1300
9    Thursday     English      Beer     4000
10   Thursday       Irish  Cocktail     2200
11   Thursday    American      Food     1800
12     Friday     English      Beer     8500
13     Friday       Irish  Cocktail     3500
14     Friday    American      Food     2500
15     Friday      French      Beer     1800
16     Friday      German      Food     1400
17   Saturday     English      Beer     9500
18   Saturday       Irish  Cocktail     4200
19   Saturday    American      Food     3000
20   Saturday      French      Beer     2200
21   Saturday      German      Food     1700
22     Sunday     English      Beer     5000
23     Sunday       Irish  Cocktail     2500
24     Sunday    American      Food     1800

In [7]:
df

          Day Nationality  Category  Revenue
0      Monday     English      Beer     2500
1      Monday       Irish      Beer     1200
2      Monday    American      Food      900
3     Tuesday     English      Beer     2800
4     Tuesday       Irish  Cocktail     1500
5     Tuesday    American      Food     1100
6   Wednesday     English      Beer     3200
7   Wednesday       Irish  Cocktail     1800
8   Wednesday    American      Food     1300
9    Thursday     English      Beer     4000
10   Thursday       Irish  Cocktail     2200
11   Thursday    American      Food     1800
12     Friday     English      Beer     8500
13     Friday       Irish  Cocktail     3500
14     Friday    American      Food     2500
15     Friday      French      Beer     1800
16     Friday      German      Food     1400
17   Saturday     English      Beer     9500
18   Saturday       Irish  Cocktail     4200
19   Saturday    American      Food     3000
20   Saturday      French      Beer     2200
21   Saturday      German      Food     1700
22     Sunday     English      Beer     5000
23     Sunday       Irish  Cocktail     2500
24     Sunday    American      Food     1800

In [8]:
df.pivot_table(values = 'Revenue', index = 'Day', columns = 'Category', aggfunc = 'sum')

Category      Beer  Cocktail    Food
Day
Friday     10300.0    3500.0  3900.0
Monday      3700.0       NaN   900.0
Saturday   11700.0    4200.0  4700.0
Sunday      5000.0    2500.0  1800.0
Thursday    4000.0    2200.0  1800.0
Tuesday     2800.0    1500.0  1100.0
Wednesday   3200.0    1800.0  1300.0

In [10]:
df.groupby(['Day', 'Category'])['Revenue'].sum()

Day        Category
Friday     Beer        10300
           Cocktail     3500
           Food         3900
Monday     Beer         3700
           Food          900
Saturday   Beer        11700
           Cocktail     4200
           Food         4700
Sunday     Beer         5000
           Cocktail     2500
           Food         1800
Thursday   Beer         4000
           Cocktail     2200
           Food         1800
Tuesday    Beer         2800
           Cocktail     1500
           Food         1100
Wednesday  Beer         3200
           Cocktail     1800
           Food         1300
Name: Revenue, dtype: int64

In [13]:
# revenue per day
df.pivot_table(values ='Revenue', index = 'Day', aggfunc = 'sum')

           Revenue
Day
Friday       17700
Monday        4600
Saturday     20600
Sunday        9300
Thursday      8000
Tuesday       5400
Wednesday     6300

In [15]:
#revenue by nationakityh
df.pivot_table(values ='Revenue', index = 'Nationality', aggfunc = 'sum')

             Revenue
Nationality
American       12400
English        35500
French          4000
German          3100
Irish          16900

In [16]:
#revenue by category
df.pivot_table(values ='Revenue', index = 'Category', aggfunc = 'sum')

          Revenue
Category
Beer        40700
Cocktail    15700
Food        15500

In [17]:
#revenue by day and nationaity
df.pivot_table(values = 'Revenue', index = 'Day', columns = 'Nationality', aggfunc = 'sum')

Nationality  American  English  French  German   Irish
Day
Friday         2500.0   8500.0  1800.0  1400.0  3500.0
Monday          900.0   2500.0     NaN     NaN  1200.0
Saturday       3000.0   9500.0  2200.0  1700.0  4200.0
Sunday         1800.0   5000.0     NaN     NaN  2500.0
Thursday       1800.0   4000.0     NaN     NaN  2200.0
Tuesday        1100.0   2800.0     NaN     NaN  1500.0
Wednesday      1300.0   3200.0     NaN     NaN  1800.0

In [21]:
#revenue by day and nationality byt using groupby method
df.groupby(['Day', 'Nationality'])['Revenue'].sum()

Day        Nationality
Friday     American       2500
           English        8500
           French         1800
           German         1400
           Irish          3500
Monday     American        900
           English        2500
           Irish          1200
Saturday   American       3000
           English        9500
           French         2200
           German         1700
           Irish          4200
Sunday     American       1800
           English        5000
           Irish          2500
Thursday   American       1800
           English        4000
           Irish          2200
Tuesday    American       1100
           English        2800
           Irish          1500
Wednesday  American       1300
           English        3200
           Irish          1800
Name: Revenue, dtype: int64

In [22]:
#revnue by day and category
df.pivot_table(values = 'Revenue', index = 'Day', columns = 'Category', aggfunc = 'sum')

Category      Beer  Cocktail    Food
Day
Friday     10300.0    3500.0  3900.0
Monday      3700.0       NaN   900.0
Saturday   11700.0    4200.0  4700.0
Sunday      5000.0    2500.0  1800.0
Thursday    4000.0    2200.0  1800.0
Tuesday     2800.0    1500.0  1100.0
Wednesday   3200.0    1800.0  1300.0