In [3]:
import pandas as pd

In [4]:
sales = { 'Day': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
           'Revenue': [1200, 1500, 1800, 2200, 3500] }

In [5]:
df= pd.DataFrame(sales)
df

         Day  Revenue
0     Monday     1200
1    Tuesday     1500
2  Wednesday     1800
3   Thursday     2200
4     Friday     3500

In [6]:
total_revenue = df['Revenue'].sum()
print("Total Revenue:", total_revenue)

Total Revenue: 10200

In [7]:
maximum_revenue = df['Revenue'].max()
print("Maximum Revenue:", maximum_revenue)

Maximum Revenue: 3500

In [8]:
the_mean_revenue = df['Revenue'].mean()
print("Mean Revenue:", the_mean_revenue)

Mean Revenue: 2040.0

In [9]:
df['Day'][df['Revenue'] == maximum_revenue]

4    Friday
Name: Day, dtype: str

In [10]:
df.loc[df["Revenue"].idxmax()]

Day        Friday
Revenue      3500
Name: 4, dtype: object

In [11]:
df.loc[df['Day'].idxmax()]

Day        Wednesday
Revenue         1800
Name: 2, dtype: object

In [12]:
df[df['Revenue']>2000]

        Day  Revenue
3  Thursday     2200
4    Friday     3500

In [13]:
df.loc[df['Revenue']>1500]

         Day  Revenue
2  Wednesday     1800
3   Thursday     2200
4     Friday     3500

In [14]:
df['Revenue']

0    1200
1    1500
2    1800
3    2200
4    3500
Name: Revenue, dtype: int64

In [15]:
weekly_revenue = df['Revenue'].sum()
print('Our weekly revenue is: ', weekly_revenue)

Our weekly revenue is:  10200

In [16]:
df['Day'][df['Revenue'].idxmax()]

'Friday'

In [17]:
df['Day'][df['Revenue']>2000]

3    Thursday
4      Friday
Name: Day, dtype: str

In [18]:
average_prformance = df['Revenue'].mean()
print('The Average Performance is :', average_prformance)

The Average Performance is : 2040.0

In [19]:
df.sort_values(by='Revenue', ascending=False)

         Day  Revenue
4     Friday     3500
3   Thursday     2200
2  Wednesday     1800
1    Tuesday     1500
0     Monday     1200

In [20]:
df.sort_values(by= 'Revenue', ascending = False).head(2)

        Day  Revenue
4    Friday     3500
3  Thursday     2200

In [21]:
df['Category'] = ['low', 'low', 'medium', 'high', 'very high']
df

         Day  Revenue   Category
0     Monday     1200        low
1    Tuesday     1500        low
2  Wednesday     1800     medium
3   Thursday     2200       high
4     Friday     3500  very high

In [23]:
df[['Day', 'Category']]

         Day   Category
0     Monday        low
1    Tuesday        low
2  Wednesday     medium
3   Thursday       high
4     Friday  very high

In [24]:
df['Day'][df['Category']== 'high']

3    Thursday
Name: Day, dtype: str

In [29]:
df[(df['Revenue']>1500) & (df['Category']== 'medium')]

         Day  Revenue Category
2  Wednesday     1800   medium

In [30]:
df[(df['Revenue'] > 2000) |(df['Category'] == 'medium')]

         Day  Revenue   Category
2  Wednesday     1800     medium
3   Thursday     2200       high
4     Friday     3500  very high