In [25]:
employees ={
    'EmployeeID':['101', '102', '103'],
    'Name':['Fadi', 'Sean', 'John']
}

In [26]:
import pandas as pd

In [27]:
print(employees)

{'EmployeeID': ['101', '102', '103'], 'Name': ['Fadi', 'Sean', 'John']}

In [28]:
sales = {
    'EmployeeID': ['101', '102', '101', '103'],
    'Revenue': [500, 700, 600, 400]
}

In [29]:
df_employees = pd.DataFrame(employees)

In [30]:
df_employees

  EmployeeID  Name
0        101  Fadi
1        102  Sean
2        103  John

In [31]:
df_sales = pd.DataFrame(sales)

In [32]:
df_sales

  EmployeeID  Revenue
0        101      500
1        102      700
2        101      600
3        103      400

In [33]:
df_employees.merge(df_sales, on = 'EmployeeID')

  EmployeeID  Name  Revenue
0        101  Fadi      500
1        101  Fadi      600
2        102  Sean      700
3        103  John      400

In [42]:
employees = {
    'EmployeeID': ['101', '102', '103', '104'],
    'Name': ['Fadi', 'Sean', 'John', 'Sara']
}
df_employees = pd.DataFrame(employees)

In [43]:
df_employees.merge(df_sales, on = 'EmployeeID')

  EmployeeID  Name  Revenue
0        101  Fadi      500
1        101  Fadi      600
2        102  Sean      700
3        103  John      400

In [44]:
df_employees.merge(df_sales, on = 'EmployeeID', how = 'left')

  EmployeeID  Name  Revenue
0        101  Fadi    500.0
1        101  Fadi    600.0
2        102  Sean    700.0
3        103  John    400.0
4        104  Sara      NaN

In [45]:
df_sales.merge(df_employees, on='EmployeeID', how='left')

  EmployeeID  Revenue  Name
0        101      500  Fadi
1        102      700  Sean
2        101      600  Fadi
3        103      400  John

In [46]:
result = df_employees.merge(df_sales, on='EmployeeID', how='left')
result

  EmployeeID  Name  Revenue
0        101  Fadi    500.0
1        101  Fadi    600.0
2        102  Sean    700.0
3        103  John    400.0
4        104  Sara      NaN